### ISSUE TITLE
Escaping of resource uris

### ISSUE THREAD

**Issue by dimaip** [flownative/flow-aws-s3#21]
This storage target does not escape special characters in filenames like `+`.
E.g. it returns this link: https://psmb-neos-resources.hb.bizmrg.com/target/sfi/c0b7e1d5d93536e0c87755e70def6ac8fe3aeecf/__IGP7679%2B.jpg
Instead of: https://psmb-neos-resources.hb.bizmrg.com/target/sfi/c0b7e1d5d93536e0c87755e70def6ac8fe3aeecf/__IGP7679+.jpg

**Comment by kdambekalns** [comment]
See #2

**Comment by kdambekalns** [comment]
TBH I don't know if this actually still is an issue…

**Comment by kdambekalns** [comment]
This should be solved with https://github.com/flownative/flow-aws-s3/blob/28ab7810bddd91111f2c9f12a6b56e726514c287/Classes/S3Target.php#L466
