### ISSUE TITLE
publishFile tries to set public-read

### ISSUE THREAD

**Issue by Lemmork** [flownative/flow-aws-s3#30]
I have a private S3-Bucket connected to cloudfront.
Adding files in the backend fails, because of the public-read argument which is set in S3Target:publishFile. ($this->s3Client->upload($this->bucketName, $objectName, $sourceStream, 'public-read', $options);)

I think this is only needed, if you want to use your public s3 path. When using cloudfront it would be nice if this argument is configurable and could be set to 'private'.

Tested with release 2.0.4 and Neos 4.3.7

**Comment by baschny** [comment]
I just stumbled over this fork which contains this enhancement: 
https://github.com/mkuiphuis/flow-aws-s3/commit/dfcc041e26d774c64331fccd9c506cbc279cdb0d

**Comment by kdambekalns** [comment]
Fixed with #32
