### ISSUE TITLE
md5 functions removed too soon

### ISSUE THREAD

**Issue by mkuiphuis** [flownative/flow-aws-s3#36]
In the S3Storage class the setMd5() isn’t called anymore when importing a resource. The current Flow version (6.3) only has the functions marked as deprecated. And they will be removed in Flow 7.0+

Reinstating these functions will allow backend users to upload media again in the Media section of Neos.
(I believe the change was made on 08 October 2020 by Daniel Lienert in this package.)

**Comment by kdambekalns** [comment]
The removal is in master only, you should be using version 2.x of this package…
