### ISSUE TITLE
HTTP 500 error - wrong return type definition

### ISSUE THREAD

**Issue by grizooo** [flownative/flow-aws-s3#60]
Hi, 

there is a wrong definition in return type in the latest version. Type must be resource or bool not only bool:

https://github.com/flownative/flow-aws-s3/blob/36ab1c6e0031d8a90c456c3ceb10fa9dcd11496d/Classes/S3Storage.php#L306

This causes a 500er error

**Comment by kdambekalns** [comment]
Oh… see https://github.com/flownative/flow-aws-s3/pull/55
