### ISSUE TITLE
publishCollection S3Target

### ISSUE THREAD

**Issue by mkuiphuis** [flownative/flow-aws-s3#7]
Just updated our system from Flow 3.0 to Flow 3.0.2. After this update, clearing the cache, and warming up the cache I got the following PHP Fatal Error:

PHP Fatal error:  Declaration of Flownative\Aws\S3\S3Target::publishCollection() must be compatible with TYPO3\Flow\Resource\Target\TargetInterface::publishCollection(TYPO3\Flow\Resource\CollectionInterface $collection) in //var/www/system/Packages/Application/Flownative.Aws.S3/Classes/S3Target.php on line 24

I got it working again by changing the code below:

```
/**
     * Publishes the whole collection to this target
     *
     * @param \TYPO3\Flow\Resource\Collection $collection The collection to publish
     * @return void
     * @throws Exception
     */
    public function publishCollection(Collection $collection)
    {
    ....
    }
```

into

```
/**
     * Publishes the whole collection to this target
     *
     * @param \TYPO3\Flow\Resource\CollectionInterface $collection The collection to publish
     * @return void
     * @throws Exception
     */
    public function publishCollection(CollectionInterface $collection)
    {
    .....
    }
```

(changed **Collection** to **CollectionInterface**)

I haven't tested this on Flow 3.0.0 or 3.0.1 though....

**Comment by kdambekalns** [comment]
Fixed since 2016-03-08 and released with version 1.1.0-beta1.
